
version: "3.9"
services:
  grafana:
    image: grafana/grafana:11.1.7-ubuntu
    ports:
      - "3000:3000"
    networks:
      - loki
    volumes:
      - grafana-data:/var/lib/grafana
      - grafana-configs:/etc/grafana
  prometheus:
    image: prom/prometheus:v2.54.1
    ports:
      - "9090:9090"
    networks:
      - loki
    volumes:
      - prom-data:/prometheus
      - prom-configs:/etc/prometheus
      - /var/lib/jenkins/workspace/Grafana/alert.rules.yml:/alertmanager/alert.rules.yml
      - /var/lib/jenkins/workspace/Grafana/prometheus.yml:/etc/prometheus/prometheus.yml
  node-exporter:
    image: prom/node-exporter:v1.8.1
    ports:
      - "9100:9100"
    networks:
      - loki
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude'
      - '^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)'
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.0
    ports:
      - "8081:8080"
    networks:
      - loki
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
  alertmanager:
    image: prom/alertmanager
    ports:
      - "9093:9093"
    networks:
      - loki
    volumes:
      - /var/lib/jenkins/workspace/Grafana/alertmanager.yml:/etc/alertmanager/alertmanager.yml
  snmp-exporter:
    image: quay.io/prometheus/snmp-exporter
    ports:
      - "9116:9116"
    networks:
      - loki
networks:
  loki:
    driver: overlay
    attachable: true
volumes:
  grafana-data:
  grafana-configs:
  prom-data:
  prom-configs: 
